global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/b07e7e49-d7de-4223-b37a-e5ea113571fc'
          send_resolved: false
